# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."notes-chrome" = {
    image = "gcr.io/zenika-hub/alpine-chrome:123";
    cmd = [ "--no-sandbox" "--disable-gpu" "--disable-dev-shm-usage" "--remote-debugging-address=0.0.0.0" "--remote-debugging-port=9222" "--hide-scrollbars" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=chrome"
      "--network=notes_default"
    ];
  };
  systemd.services."podman-notes-chrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-notes_default.service"
    ];
    requires = [
      "podman-network-notes_default.service"
    ];
    partOf = [
      "podman-compose-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-notes-root.target"
    ];
  };
  virtualisation.oci-containers.containers."notes-meilisearch" = {
    image = "getmeili/meilisearch:v1.11.1";
    environment = {
      "HOARDER_VERSION" = "0.22.0";
      "MEILI_MASTER_KEY" = "/TN9VMPm0K9jbGUvVD49egAQo/7WSDMs/51+2prl1Ij/LHZG";
      "MEILI_NO_ANALYTICS" = "true";
      "NEXTAUTH_SECRET" = "W8L5/Ik2lBzlF46rh0Bp+1/RDSfs6It8Vk0WCwoeZijOOyjA";
      "NEXTAUTH_URL" = "http://0.0.0.0:3000";
    };
    volumes = [
      "notes_meilisearch:/meili_data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=meilisearch"
      "--network=notes_default"
    ];
  };
  systemd.services."podman-notes-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-notes_default.service"
      "podman-volume-notes_meilisearch.service"
    ];
    requires = [
      "podman-network-notes_default.service"
      "podman-volume-notes_meilisearch.service"
    ];
    partOf = [
      "podman-compose-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-notes-root.target"
    ];
  };
  virtualisation.oci-containers.containers."notes-web" = {
    image = "ghcr.io/hoarder-app/hoarder:0.22.0";
    environment = {
      "BROWSER_WEB_URL" = "http://chrome:9222";
      "DATA_DIR" = "/data";
      "HOARDER_VERSION" = "0.22.0";
      "MEILI_ADDR" = "http://meilisearch:7700";
      "MEILI_MASTER_KEY" = "/TN9VMPm0K9jbGUvVD49egAQo/7WSDMs/51+2prl1Ij/LHZG";
      "NEXTAUTH_SECRET" = "W8L5/Ik2lBzlF46rh0Bp+1/RDSfs6It8Vk0WCwoeZijOOyjA";
      "NEXTAUTH_URL" = "http://0.0.0.0:3000";
    };
    volumes = [
      "/home/danielgm/Documents/Services/Hoarder/data:/data:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web"
      "--network=notes_default"
    ];
  };
  systemd.services."podman-notes-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-notes_default.service"
    ];
    requires = [
      "podman-network-notes_default.service"
    ];
    partOf = [
      "podman-compose-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-notes-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-notes_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f notes_default";
    };
    script = ''
      podman network inspect notes_default || podman network create notes_default
    '';
    partOf = [ "podman-compose-notes-root.target" ];
    wantedBy = [ "podman-compose-notes-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-notes_meilisearch" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect notes_meilisearch || podman volume create notes_meilisearch
    '';
    partOf = [ "podman-compose-notes-root.target" ];
    wantedBy = [ "podman-compose-notes-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-notes-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
