
# Auto-generated using compose2nix v0.2.0-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };
  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."lobe-chat" = {
    image = "lobehub/lobe-chat";
    environment = {
      ACCESS_CODE = "lobe66";
      OPENAI_API_KEY = "sk-xxxx";
      OPENAI_PROXY_URL = "https://api-proxy.com/v1";
    };
    ports = [
      "3210:3210/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lobe-chat"
      "--network=lobe_chat_default"
    ];
  };
  systemd.services."podman-lobe-chat" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
    };
    after = [
      "podman-network-lobe_chat_default.service"
    ];
    requires = [
      "podman-network-lobe_chat_default.service"
    ];
    partOf = [
      "podman-compose-lobe_chat.target"
    ];
    wantedBy = [
      "podman-compose-lobe_chat.target"
    ];
  };
  # Networks
  systemd.services."podman-network-lobe_chat_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f lobe_chat_default";
    };
    script = ''
      podman network inspect lobe_chat_default || podman network create lobe_chat_default
    '';
    partOf = [ "podman-compose-lobe_chat.target" ];
    wantedBy = [ "podman-compose-lobe_chat.target" ];
  };

  # Volumes
  systemd.services."podman-volume-lobe_chat" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect lobe_chat || podman volume create lobe_chat
    '';
    partOf = [ "podman-compose-lobe_chat.target" ];
    wantedBy = [ "podman-compose-lobe_chat.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-lobe_chat-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
