# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."notes-db" = {
    image = "mysql:5.7";
    environment = {
      "MYSQL_DATABASE" = "caliche_DB";
      "MYSQL_PASSWORD" = "lacalida";
      "MYSQL_ROOT_PASSWORD" = "lacalida";
      "MYSQL_USER" = "caliche";
    };
    volumes = [
      "notes_my-db:/var/lib/mysql:rw"
    ];
    ports = [
      "3307:3306/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=notes_my_network"
    ];
  };
  systemd.services."podman-notes-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-notes_my_network.service"
      "podman-volume-notes_my-db.service"
    ];
    requires = [
      "podman-network-notes_my_network.service"
      "podman-volume-notes_my-db.service"
    ];
    partOf = [
      "podman-compose-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-notes-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-notes_my_network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f notes_my_network";
    };
    script = ''
      podman network inspect notes_my_network || podman network create notes_my_network --driver=bridge
    '';
    partOf = [ "podman-compose-notes-root.target" ];
    wantedBy = [ "podman-compose-notes-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-notes_my-db" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect notes_my-db || podman volume create notes_my-db
    '';
    partOf = [ "podman-compose-notes-root.target" ];
    wantedBy = [ "podman-compose-notes-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-notes-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
