# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."plex" = {
    #image = "lscr.io/linuxserver/plex:latest";
    image = "lscr.io/linuxserver/plex:1.41.3.9314-a0bfb8370-ls250";
    environment = {
      "PGID" = "1000";
      #"PLEX_CLAIM" = "claim-uUNNwqVD2Jdj9UKK6f4F";
      "PUID" = "1000";
      "TZ" = "America/Bogota";
    };
    volumes = [
      "/home/danielgm/Documents/Services/plex/config:/config:rw"
      "/home/danielgm/Media/anime:/anime:rw"
      "/home/danielgm/Media/movies:/movies:rw"
      "/home/danielgm/Media/tv:/tv:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--network=host"
    ];
  };
  systemd.services."podman-plex" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-notes-root.target"
    ];
    wantedBy = [
      "podman-compose-notes-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-notes-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
