# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:16-alpine";
    environment = {
      "POSTGRES_DB" = "realplus";
      "POSTGRES_PASSWORD" = "S3cret";
      "POSTGRES_USER" = "dgmdba";
    };
    volumes = [
      "/home/danielgm/Documents/Services/postgresql/var:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "6969:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=postgres"
      "--network=postgres_default"
    ];
  };
  systemd.services."podman-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-postgres_default.service"
    ];
    requires = [
      "podman-network-postgres_default.service"
    ];
    partOf = [
      "podman-compose-postgres-root.target"
    ];
    wantedBy = [
      "podman-compose-postgres-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-postgres_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f postgres_default";
    };
    script = ''
      podman network inspect postgres_default || podman network create postgres_default
    '';
    partOf = [ "podman-compose-postgres-root.target" ];
    wantedBy = [ "podman-compose-postgres-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-postgres-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
