#!/bin/sh

# Path to your wallpaper image
wallpaper="/home/danielgm/.dots-flakes/wallpapers/coclors.png"

# Set the wallpaper using feh
feh --bg-fill "$wallpaper"

# Set the wallpaper mode (optional)
#feh --bg-fill --no-fehbg --randomize "$wallpaper"

# Set the wallpaper for each monitor (optional)
#feh --bg-fill --no-fehbg --auto-scale --randomize --recursive --bg-fill "$wallpaper" -- "$wallpaper_directory"

# Additional configuration or commands (optional)
# ...

# Execute dwm
#exec dwm
